<?php
/**
 * CheckItOut extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement for EcomDev Premium Extensions.
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.ecomdev.org/license-agreement
 *
 * @category   EcomDev
 * @package    EcomDev_CheckItOut
 * @copyright  Copyright (c) 2013 EcomDev BV (http://www.ecomdev.org)
 * @license    http://www.ecomdev.org/license-agreement  End User License Agreement for EcomDev Premium Extensions.
 * @author     Ivan Chepurnyi <ivan.chepurnyi@ecomdev.org>
 */

/**
 * Checkout template
 */
/* @var $this EcomDev_CheckItOut_Block_Js */
?>
<script type="text/javascript">
window.countryRegions=<?php echo $this->getRegionJson(); ?>;
window.currentPaymentMethod = '<?php echo $this->jsQuoteEscape($this->getQuote()->getPayment()->getMethod());?>';
window.currentCheckoutMethod = '<?php echo $this->jsQuoteEscape($this->getQuote()->getData('checkout_method'));?>';
</script>