<?php if ($this->helper('ecomdev_checkitout')->isConfirmPopUp()): ?>
<div class="checkout-step" id="confirmation-window" style="display:none">
    <div class="step-header"><?php echo $this->getStepName(); ?></div>
    <div class="step-content"></div>
    <div class="step-loading" style="display:none;"><span><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading step data...') ?>" title="<?php echo $this->__('Loading step data...') ?>" class="v-middle" /> <?php echo $this->helper('ecomdev_checkitout')->__('Loading Order Information...') ?></span></div>
</div>

<script type="text/javascript">
var confirmPopUp = new ConfirmPopUp('confirmation-window', '<?php echo $this->getUrl('*/*/confirm');?>');
</script>
<?php endif; ?>