<?php
/**
 * CheckItOut extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * @category   EcomDev
 * @package    EcomDev_CheckItOut
 * @copyright  Copyright (c) 2016 EcomDev BV (http://www.ecomdev.org)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Ivan Chepurnyi <ivan.chepurnyi@ecomdev.org>
 */

/**
 * Checkout layout step template
 */
/* @var $this EcomDev_CheckItOut_Block_Layout_Step_Abstract */
?>
<?php if ($this->isVisible()): // If Children Visible?>
<div class="<?php echo $this->escapeHtml($this->getClassName());?> <?php if ($this->getPositionCode()): ?><?php echo $this->escapeHtml($this->getPositionCode());?><?php endif;?>">
    <div class="page-title">
        <h1><?php echo $this->helper('checkout')->__('Checkout') ?></h1>
        <?php echo $this->getStepContent(); ?>
    </div>
</div>
<?php else:?>
<div class="page-title">
    <h1><?php echo $this->helper('checkout')->__('Checkout') ?></h1>
</div>
<?php endif;?>
