<?php
/**
 * CheckItOut extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   EcomDev
 * @package    EcomDev_CheckItOut
 * @copyright  Copyright (c) 2011 EcomDev BV (http://www.ecomdev.org)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Ivan Chepurnyi <ivan.chepurnyi@ecomdev.org>
 */
 /**
  * Checkout template
  */
 /* @var $this EcomDev_CheckItOut_Block_Checkout_Layout */
?>
<?php if ($this->displayContainer()): ?>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<div class="checkitout" id="checkout-layout">
<div class="content">
<?php endif; ?>
<?php if ($this->displayLayout('top')):?>
<!-- top checkout layout start -->
<div class="layout-top">
<div class="page-title">
    <h1><?php echo $this->helper('checkout')->__('Checkout') ?></h1>
<?php $_index = 0;?>
<?php foreach ($this->getCheckoutBlocksByLayout('top') as $_stepId => $_step): ?>
<?php if (!$this->displayStep($_stepId)): continue; endif; ?>
<?php $_isSecond = ((++$_index % 2 == 0) ? 'second' : 'first');?>
<div class="checkout-step <?php echo $_isSecond; ?>" id="checkout-step-<?php echo $_stepId;?>">
<div class="step-content" id="checkout-step-<?php echo $_stepId;?>-content"><?php echo $this->getStepBlockHtml($_stepId); ?></div>
</div>
<?php endforeach;?>
</div>
</div>
<!-- top checkout layout end -->
<?php else:?>
<div class="page-title">
    <h1><?php echo $this->helper('checkout')->__('Checkout') ?></h1>
</div>
<?php endif;?>
<div class="clear"></div>
<div class="max-height">
<?php if ($this->displayLayout('address')):?>
<!-- address checkout layout start -->
<div class="layout-address">
<div class="checkout-step" id="checkout-step-address">
<div class="step-header" id="checkout-step-address-header"><span class="number">1</span><?php echo $this->helper('ecomdev_checkitout')->__('Address'); ?></div>
<div class="step-content" id="checkout-step-address-content">
<?php $_index = 0;?>
<?php foreach ($this->getCheckoutBlocksByLayout('address') as $_stepId => $_step): ?>
<?php if (!$this->displayStep($_stepId)): continue; endif; ?>
<?php $_isSecond = ((++$_index % 2 == 0) ? 'second' : 'first');?>
<div class="checkout-step <?php echo $_isSecond; ?>" id="checkout-step-<?php echo $_stepId;?>">
<div class="step-header" id="checkout-step-<?php echo $_stepId;?>-header"><?php echo $_step['label']; ?></div>
<div class="step-content" id="checkout-step-<?php echo $_stepId;?>-content"><?php echo $this->getStepBlockHtml($_stepId); ?></div>
</div>
<?php endforeach;?>
</div>
</div>
</div>
<!-- address checkout layout end -->
<?php endif; ?>
<?php $_stepNumber = 2;?>
<?php $_subLayouts = array('right', 'right-bottom');?>
<div class="layout-content">
<?php foreach ($_subLayouts as $_position): ?>
<?php if (!$this->displayLayout($_position)): continue; endif;?>
<!-- <?php echo $_position;?> checkout layout start -->
<div class="layout-<?php echo $_position;?>">
<?php $_index = 0;?>
<?php foreach ($this->getCheckoutBlocksByLayout($_position) as $_stepId => $_step): ?>
<?php if (!$this->displayStep($_stepId)): continue; endif; ?>
<?php $_isSecond = ((++$_index % 2 == 0) ? 'second' : 'first');?>
<div class="checkout-step <?php echo $_isSecond; ?>" id="checkout-step-<?php echo $_stepId;?>">
<div class="step-header" id="checkout-step-<?php echo $_stepId;?>-header"><span class="number"><?php echo $_stepNumber ++; ?></span><?php echo $_step['label']; ?></div>
<div class="step-content" id="checkout-step-<?php echo $_stepId;?>-content"><?php echo $this->getStepBlockHtml($_stepId); ?></div>
<div class="step-loading" style="display:none;"><span><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading step data...') ?>" title="<?php echo $this->__('Loading step data...') ?>" class="v-middle" /> <?php echo $this->__('Loading step data...') ?></span></div>
</div>
<?php endforeach;?>
</div>
<!-- <?php echo $_position;?> checkout layout end -->
<?php endforeach;?>
</div>
</div>
<?php if ($this->displayContainer()): ?>
</div>
<?php if ($this->helper('ecomdev_checkitout')->isConfirmPopUp()):?>
<?php echo $this->getChildHtml('confirm');?>
<?php endif;?>
<?php if ($this->getShippingMethod()):?>
<script type="text/javascript">
shippingMethod.lastSubmitted = {shipping_method: '<?php echo $this->jsQuoteEscape($this->getShippingMethod());?>'};
</script>
<?php endif;?>
</div>
<div class="checkitout-checkout-loading" style="display:none;"><span><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?></span></div>
<div class="checkitout-checkout-overlay" ></div>
<script type="text/javascript">
var lastPrice, quoteBaseGrandTotal;
var checkout = new EcomDev.CheckItOut({
    reload: '<?php echo $this->getUrl('checkout/onepage/steps');?>',
    save: '<?php echo $this->getUrl('checkout/onepage/saveOrder');?>',
    success: '<?php echo $this->getUrl('checkout/onepage/success');?>',
    container: 'checkout-layout',
    useForShippingLabel: '<?php echo $this->jsQuoteEscape($this->helper('ecomdev_checkitout')->__('Use same address for shipping'));?>',
    createAccountLabel: '<?php echo $this->jsQuoteEscape($this->helper('ecomdev_checkitout')->__('Create an account for me'));?>',
    additionalUrl: '<?php echo $this->getUrl('*/*/getAdditional');?>',
    additionalContainer: $('onepage-checkout-shipping-method-additional-load'),
    isAllowedGuestCheckout: <?php echo (int)$this->helper('ecomdev_checkitout')->isAllowedGuestCheckout();?>,
    stepHash: <?php echo $this->getHashJson(); ?>
});
</script>
<?php endif; ?>