<?php
/**
 * Friendly checkout link template,
 * inherits one page checkout functionality
 */
?>
<?php if ($this->isPossibleOnepageCheckout()):?>
    <button type="button" title="<?php echo $this->helper('checkout')->__('Proceed to Checkout') ?>" class="button btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getUrl('checkout/friendly') ?>';"><span><span><?php echo $this->helper('checkout')->__('Proceed to Checkout') ?></span></span></button>
<?php endif?>
