<?php
/**
 * CheckItOut extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement for EcomDev Premium Extensions.
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.ecomdev.org/license-agreement
 *
 * @category   EcomDev
 * @package    EcomDev_CheckItOut
 * @copyright  Copyright (c) 2013 EcomDev BV (http://www.ecomdev.org)
 * @license    http://www.ecomdev.org/license-agreement  End User License Agreement for EcomDev Premium Extensions.
 * @author     Ivan Chepurnyi <ivan.chepurnyi@ecomdev.org>
 */
?>
<div id="login-step">
<?php echo $this->helper('ecomdev_checkitout')->__('Do you have an account?');?> &nbsp;
<button class="button popup-trigger"><span><span><?php echo $this->__('Login') ?></span></span></button>
<div class="popup" style="display:none" id="login-step-popup">
    <div class="popup-title"><?php echo $this->__('Login') ?> <button class="button popup-close"><span><span><?php echo $this->__('X') ?></span></span></button></div>
    <div class="popup-content"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
    <fieldset>
        <p><?php echo $this->__('Please log in below:') ?></p>
        <ul class="form-list">
            <li>
                <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                </div>
            </li>
            <li>
                <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                <div class="input-box">
                    <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                </div>
            </li>
            <li>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                <button type="submit" class="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
                <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
            </li>
        </ul>
    </fieldset>
    </form>
    </div>
</div>
<div style="display:none">
    <ul class="form-list">
        <li class="control">
            <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
        </li>
        <li class="control">
            <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
        </li>
    </ul>
</div>
</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    var loginStep = new LoginStep('login-step', '<?php echo $this->getUrl('*/*/saveMethod') ?>');
//]]>
</script>
