<?php
/**
 * CheckItOut extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement for EcomDev Premium Extensions.
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.ecomdev.org/license-agreement
 *
 * @category   EcomDev
 * @package    EcomDev_CheckItOut
 * @copyright  Copyright (c) 2013 EcomDev BV (http://www.ecomdev.org)
 * @license    http://www.ecomdev.org/license-agreement  End User License Agreement for EcomDev Premium Extensions.
 * @author     Ivan Chepurnyi <ivan.chepurnyi@ecomdev.org>
 */

/**
 * Checkout template
 */
/* @var $this EcomDev_CheckItOut_Block_Js */
?>
<div class="checkitout-checkout-loading" style="display:none;"><span><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?></span></div>
<div class="checkitout-checkout-overlay" ></div>
<script type="text/javascript">

    <?php if ($this->getShippingMethodJson()):?>
    if (window.shippingMethod) {
        shippingMethod.lastSubmitted = <?php echo $this->getShippingMethodJson();?>;
    }
    <?php endif;?>

    var lastPrice, quoteBaseGrandTotal;
    var checkout = new EcomDev.CheckItOut({
        reload: '<?php echo $this->getUrl('checkout/onepage/steps');?>',
        save: '<?php echo $this->getUrl('checkout/onepage/saveOrder');?>',
        success: '<?php echo $this->getUrl('checkout/onepage/success');?>',
        container: 'checkout-layout',
        useForShippingLabel: '<?php echo $this->jsQuoteEscape($this->helper('ecomdev_checkitout')->__('Use same address for shipping'));?>',
        createAccountLabel: '<?php echo $this->jsQuoteEscape($this->helper('ecomdev_checkitout')->__('Create an account for me'));?>',
        additionalUrl: '<?php echo $this->getUrl('*/*/getAdditional');?>',
        additionalContainer: $('onepage-checkout-shipping-method-additional-load'),
        isAllowedGuestCheckout: <?php echo (int)$this->isAllowedGuestCheckout();?>,
        stepHash: <?php echo $this->getHashJson(); ?>,
        preloadedHtml: <?php echo $this->getStepsJson();?>,
        useClassForHide: true,
        currentPaymentMethod: '<?php echo $this->jsQuoteEscape($this->getQuote()->getPayment()->getMethod());?>',
        popUpOutside: true,
        overlayOpacity: 0.8,
        maskOpacity: 0.8
    });
</script>