<?php
/**
 * CheckItOut extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement for EcomDev Premium Extensions.
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.ecomdev.org/license-agreement
 *
 * @category   EcomDev
 * @package    EcomDev_CheckItOut
 * @copyright  Copyright (c) 2015 EcomDev BV (http://www.ecomdev.org)
 * @license    http://www.ecomdev.org/license-agreement  End User License Agreement for EcomDev Premium Extensions.
 * @author     Ivan Chepurnyi <ivan.chepurnyi@ecomdev.org>
 */
/* @var $this EcomDev_CheckItOut_Block_Layout_Step_Default */
?>
<?php if ($this->helper('ecomdev_checkitout')->isConfirmPopUp()): ?>
<div class="checkout-step" id="confirmation-window" style="display:none">
    <div class="step-header"><?php echo $this->getStepName(); ?></div>
    <div class="step-content"></div>
    <div class="step-loading" style="display:none;"><span><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading step data...') ?>" title="<?php echo $this->__('Loading step data...') ?>" class="v-middle" /> <?php echo $this->helper('ecomdev_checkitout')->__('Loading Order Information...') ?></span></div>
</div>

<script type="text/javascript">
var confirmPopUp = new ConfirmPopUp('confirmation-window', '<?php echo $this->getUrl('*/*/confirm');?>');
</script>
<?php endif; ?>
