<?php
/**
 * CheckItOut extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * @category   EcomDev
 * @package    EcomDev_CheckItOut
 * @copyright  Copyright (c) 2016 EcomDev BV (http://www.ecomdev.org)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Ivan Chepurnyi <ivan.chepurnyi@ecomdev.org>
 */

/**
 * Checkout coupone code step template
 */
/* @var $this EcomDev_CheckItOut_Block_Layout_Step_Coupon*/
?>
<div class="<?php echo $this->getClassName();?> <?php if ($this->getPositionCode()): ?><?php echo $this->escapeHtml($this->getPositionCode());?><?php endif;?>" id="checkout-step-<?php echo $this->getStepCode();?>">
    <div class="step-content" id="checkout-step-<?php echo $this->getStepCode();?>-content">
        <form action="" id="checkout-step-<?php echo $this->getStepCode();?>-form">

            <ul class="form-list">
                <li>
                    <label for="coupon" class="required"><em>*</em><?php echo $this->__('Coupon Code') ?></label>
                    <div class="input-box">
                        <input type="text" name="coupon" id="coupon" title="<?php echo $this->__('Coupon Code') ?>" class="input-text required-entry" />
                    </div>
                </li>
                <li class="control">
                    <button type="button" class="button apply" title="<?php echo $this->__('Apply') ?>"><span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
                    <button type="button" class="button remove" title="<?php echo $this->__('Remove') ?>"><span><span><?php echo $this->__('Remove Coupon') ?></span></span></button>
                </li>
            </ul>
            <div class="clear"></div>
        </form>
    </div>
</div>
<script type="text/javascript">
    var couponCode = new CouponCode('checkout-step-<?php echo $this->getStepCode();?>', <?php echo $this->getCouponJson();?>);
</script>
