<?php
/**
 * CheckItOut extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement for EcomDev Premium Extensions.
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.ecomdev.org/license-agreement
 *
 * @category   EcomDev
 * @package    EcomDev_CheckItOut
 * @copyright  Copyright (c) 2012 EcomDev BV (http://www.ecomdev.org)
 * @license    http://www.ecomdev.org/license-agreement  End User License Agreement for EcomDev Premium Extensions.
 * @author     Ivan Chepurnyi <ivan.chepurnyi@ecomdev.org>
 */

/* @var $this Mage_Checkout_Block_Onepage_Review */
?>
<?php if ($this->helper('ecomdev_checkitout')->isCustomerCommentAllowed()):?>
<ul class="form-list">
    <li class="order-comments">
        <label for="order-comments"><?php echo $this->helper('ecomdev_checkitout')->__('Comments') ?></label>
        <div class="input-box">
            <textarea class="input-text"
                id="order-comments"
                name="order[customer_comment]"><?php echo $this->escapeHtml($this->getQuote()->getCustomerComment());?></textarea>
        </div>
    </li>
</ul>
<?php endif;?>
<?php if ($this->helper('ecomdev_checkitout')->isNewsletterCheckboxDisplay()):?>
<ul class="form-list">
    <li class="control">
         <input id="newsletter-checkbox" class="checkbox" type="checkbox" name="newsletter" value="1" <?php if ($this->helper('ecomdev_checkitout')->isNewsletterCheckboxChecked()):?> checked="checked" <?php endif;?>/>
         <label for="newsletter-checkbox"><?php echo $this->helper('ecomdev_checkitout')->__('Sign Up for Newsletter') ?></label>
    </li>
</ul>
<?php endif;?>