<?php
/**
 * CheckItOut extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   EcomDev
 * @package    EcomDev_CheckItOut
 * @copyright  Copyright (c) 2011 EcomDev BV (http://www.ecomdev.org)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Ivan Chepurnyi <ivan.chepurnyi@ecomdev.org>
 */
 /**
  * Checkout layout container template
  */
 /* @var $this EcomDev_CheckItOut_Block_Checkout_Layout */
?>
<?php if ($this->displayContainer()): ?>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<div class="checkitout <?php echo $this->htmlEscape($this->getLayoutClassName());?>" id="checkout-layout">
<div class="content">
<?php endif; ?>
<?php echo $this->getChildHtml('', true, true);?>
<?php if ($this->displayContainer()): ?>
</div>
<?php if ($this->helper('ecomdev_checkitout')->isConfirmPopUp()):?>
<?php echo $this->getChildHtml('confirm');?>
<?php endif;?>
<?php if ($this->getShippingMethod()):?>
<script type="text/javascript">
shippingMethod.lastSubmitted = {shipping_method: '<?php echo $this->jsQuoteEscape($this->getShippingMethod());?>'};
</script>
<?php endif;?>
</div>
<div class="checkitout-checkout-loading" style="display:none;"><span><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?></span></div>
<div class="checkitout-checkout-overlay" ></div>
<script type="text/javascript">
var lastPrice, quoteBaseGrandTotal;
var checkout = new EcomDev.CheckItOut({
    reload: '<?php echo $this->getUrl('checkout/onepage/steps');?>',
    save: '<?php echo $this->getUrl('checkout/onepage/saveOrder');?>',
    success: '<?php echo $this->getUrl('checkout/onepage/success');?>',
    container: 'checkout-layout',
    useForShippingLabel: '<?php echo $this->jsQuoteEscape($this->helper('ecomdev_checkitout')->__('Use same address for shipping'));?>',
    createAccountLabel: '<?php echo $this->jsQuoteEscape($this->helper('ecomdev_checkitout')->__('Create an account for me'));?>',
    additionalUrl: '<?php echo $this->getUrl('*/*/getAdditional');?>',
    additionalContainer: $('onepage-checkout-shipping-method-additional-load'),
    isAllowedGuestCheckout: <?php echo (int)$this->helper('ecomdev_checkitout')->isAllowedGuestCheckout();?>,
    stepHash: <?php echo $this->getHashJson(); ?>
});
</script>
<?php endif; ?>

