<?php
/**
 * CheckItOut extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   EcomDev
 * @package    EcomDev_CheckItOut
 * @copyright  Copyright (c) 2011 EcomDev BV (http://www.ecomdev.org)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Ivan Chepurnyi <ivan.chepurnyi@ecomdev.org>
 */
 /**
  * Checkout layout step template
  */
 /* @var $this Mage_Core_Block_Template */
?>
<div class="checkitout" id="checkout-layout">
<div class="content">
<?php echo $this->getChildHtml('container_top');?>
<?php echo $this->getChildHtml('container_middle');?>
</div>
<?php echo $this->getChildHtml('container_bottom');?>
</div>